import React from 'react';
import {
  FaUtensils,
  FaCar,
  FaShoppingBag,
  FaBolt,
  FaGamepad,
  FaHeartbeat,
  FaGraduationCap,
  FaCartPlus,
  FaHome,
  FaEllipsisH,
  FaMoneyBillWave,
  FaLaptopCode,
  FaChartLine,
  FaBriefcase,
  FaGift,
  FaCoins,
  FaTag,
  FaCreditCard,
  FaMoneyCheckAlt,
  FaUniversity,
  FaMobileAlt,
  FaExchangeAlt,
  FaUsers,
  FaHistory,
  FaBullseye,
  FaCalendarAlt,
  FaPiggyBank,
  FaChartPie,
  FaReceipt,
  FaThLarge,
} from 'react-icons/fa';

const iconMap = {
  FaUtensils,
  FaCar,
  FaShoppingBag,
  FaBolt,
  FaGamepad,
  FaHeartbeat,
  FaGraduationCap,
  FaCartPlus,
  FaHome,
  FaEllipsisH,
  FaMoneyBillWave,
  FaLaptopCode,
  FaChartLine,
  FaBriefcase,
  FaGift,
  FaCoins,
  FaTag,
  FaCreditCard,
  FaMoneyCheckAlt,
  FaUniversity,
  FaMobileAlt,
  FaExchangeAlt,
  FaUsers,
  FaHistory,
  FaBullseye,
  FaCalendarAlt,
  FaPiggyBank,
  FaChartPie,
  FaReceipt,
  FaThLarge,
};

export const getCategoryIcon = (iconName, props = {}) => {
  const IconComponent = iconMap[iconName] || FaTag;
  return <IconComponent {...props} />;
};

export const AVAILABLE_ICONS = [
  'FaUtensils',
  'FaCar',
  'FaShoppingBag',
  'FaBolt',
  'FaGamepad',
  'FaHeartbeat',
  'FaGraduationCap',
  'FaCartPlus',
  'FaHome',
  'FaMoneyBillWave',
  'FaLaptopCode',
  'FaChartLine',
  'FaBriefcase',
  'FaGift',
  'FaCoins',
  'FaTag',
];
